const folderContainer = document.getElementById('folderContainer')
const currFolder = document.getElementById('currFolder')
const submitForm = document.getElementById('controlFolder')
const titleFolder = document.getElementById('titleFolder')
const controlFolder = document.getElementById('controlFolder')